#!/usr/bin/env bash
# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
new1="location /redirect_me {\\nrewrite ^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\\n}"
sudo sed -i "30i $new1" /etc/nginx/sites-available/default
