#!/usr/bin/env bash
# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
new1="location /redirect_me {\\nrewrite ^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\\n}"
sudo sed -i "40i $new1" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/own_404.html
own_404="error_page 404 /own_404.html;\nlocation = /own_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "44i $own_404" /etc/nginx/sites-available/default
service nginx start
