#!/usr/bin/env bash
# script for set a new web server 02
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent' /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo service nginx start
