#!/usr/bin/env bash
# see the task for requirements
echo $$ > /var/run/holbertonscript.pid
trap 'echo I hate the kill command ; rm '"/var/run/holbertonscript.pid"' ; exit' SIGTERM SIGQUIT
trap 'echo Y U no love me?!' SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
