#!/usr/bin/env bash
# script for the fizzbuzz exercise
n=1
while [ $n -le 100 ]; do
	if [ $((n%5)) -eq 0 ] && [ $((n%3)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((n%5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((n%3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo "$n"
	fi
	((n++))
done
