#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd,
# using the while loop + IFS.
IFS=':'
while read -r USERNAME PASSWORD USER_ID GROUP_ID USERNAME_F HOMEDIR LOGINSHELL;
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOMEDIR and rides $LOGINSHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USERNAME_F"
done </etc/passwd
