#!/usr/bin/env bash
# this script displays Holberton School 10 times with an until loop.
i=0
while [ $i -lt 10 ];
do
	if [ "$i" -eq 3 ]; then
		echo "bad luck"
	elif [ "$i" -eq 7 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
