#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes using while loop
i=0
while [ "$i" -lt 13 ]; do
	echo "Hour: $i"
	j=1
	while [ "$j" -le 59 ]; do
		echo "$j"
		((j++))
	done
	((i++))
done
