#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes using while loop
i=0
j=1
while [ "$i" -le 13 ]; do
	while [ "$j" -le 59 ]; do
		echo "$j"
		((j++))
	done
	if [ "$i" -lt 13 ]
	then
		echo "Hour: $i"
	fi
	j=1
	((i++))
done

